### ISSUE TITLE
connect to mpd

### ISSUE THREAD

**Issue by jimToo** [heddevanderlugt/MAUI---MPD-Audio-User-Interface#1]
@heddevanderlugt 

Seems like maui.py can not connect to mpd?

`pi@moode:/usr/local/maui` $ sudo python3 maui.py --test mpd
{}
connecting to Music Play Daemon (MPD)
host:  localhost     port:  6600			# default MPD port number
could not connect to Music Player Daemon, is it running?
Check: sudo systemctl status mpd
pi@moode:/usr/local/maui $ sudo systemctl status mpd
● mpd.service - Music Player Daemon
   Loaded: loaded (/lib/systemd/system/mpd.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-05-06 13:15:20 CEST; 1h 7min ago
 Main PID: 1307 (mpd)
    Tasks: 6 (limit: 2062)
   CGroup: /system.slice/mpd.service
           └─1307 /usr/local/bin/mpd --no-daemon /etc/mpd.conf

May 06 13:15:20 moode systemd[1]: Started Music Player `Daemon.`

I'm using mpd version 0.22.6.

**Comment by heddevanderlugt** [comment]
Maybe MDP player is not up and running yet. I takes MDP player some time to
startup. Maybe it is using a different port?

Op do 6 mei 2021 om 14:35 schreef jimToo ***@***.***>:

**Comment by heddevanderlugt** [comment]
I think you changed the localhost ip address (127.0.0.1) to 'localhost'. I have not tried this myself. Can you try this with the standard INI file org change the host back to 127.0.0.1.

**Comment by jimToo** [comment]
thanks for replay.

--> I've done a complete fresh installation of moode (v. 7.2.0):
&nbsp;

**Install of of python3 + the three modules (gpiozero, configparser, python-mpd2):**

`pi@moode:~ $ sudo apt install python3`
`python3 is already the newest version (3.7.3-1).`

`pi@moode:~ $ sudo python3 -m pip install pip`
`Requirement already satisfied: pip in /usr/lib/python3/dist-packages (18.1)`

`pi@moode:~ $ sudo python3 -m pip install --upgrade pip`
`Successfully installed pip-21.1.1`

`pi@moode:~ $ sudo pip install python-mpd2`
`Successfully installed python-mpd2-3.0.4`

`pi@moode:~ $ sudo pip install gpiozero`
`Successfully installed colorzero-2.0 gpiozero-1.6.2`

`pi@moode:~ $ sudo pip install configparser`
`Successfully installed configparser-5.0.2`

&nbsp;

**place scripts in /usr/local/maui:**

`pi@moode:/usr/local/maui $ ls -l
total 36`

- -rwxr-xr-x 1 root root  4001 May  6 11:42 buttons.py
- -rwxr-xr-x 1 root root  5973 May  6 11:42 lcdzero.py
- -rwxr-xr-x 1 root root  1279 May  6 11:42 maui.ini
- -rwxr-xr-x 1 root root 10324 May  6 11:47 maui.py
- -rwxr-xr-x 1 root root  5031 May  6 11:42 mpdi.py

&nbsp;
**no change of any script nor mau.ini:**

`pi@moode:/usr/local/maui $ sudo python3 maui.py --test mpd`
`Traceback (most recent call last):`
  `File "maui.py", line 253, in <module>`
   ` maui = MAUI()`
  `File "maui.py", line 102, in __init__`
    `self.read_config()`
`  File "maui.py", line 143, in read_config`
    `self.mpd = MPDi( self.config[self.musicinfo]["HOST"], self.config[self.musicinfo]["PORT"] )`
 ` File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__`
   ` raise KeyError(key)`
`KeyError: 'MPD\t\t\t# read music player data from MPD section'`

&nbsp;
**After change line 143 to ...MPDi( self.config["MPD"]["HOST"], self.config["MPD"]["PORT"] ):**

`pi@moode:/usr/local/maui $ sudo python3 maui.py --test mpd`
`GPIO5 info			# changes display from artist/song to ip number and vise versa`
GPIO12 shutdown			# shutsdown rasperry (same as shell shutdown), reboot hitting gpio03`
GPIO12HOLD poweroff		# powers off raspberry (same as shell poweroff), reboot by disconnect/reconnect `power
GPIO16 next			# music player daemon, next song on playlist`
GPIO13 previous			# music player daemon, previous song on playlist`
GPIO6 pause			# music player daemon, toggle pause/play`
GPIO17 toggleplaystop		# music player daemon, toggle stop/start`
{'GPIO5': 'info\t\t\t# changes display from artist/song to ip number and vise versa', 'GPIO12': 'shutdown\t\t\t# shutsdown rasperry (same as shell shutdown), reboot hitting gpio03', 'GPIO12HOLD': 'poweroff\t\t# powers off raspberry (same as shell poweroff), reboot by disconnect/reconnect power', 'GPIO16': 'next\t\t\t# music player daemon, next song on playlist', 'GPIO13': 'previous\t\t\t# music player daemon, previous song on playlist', 'GPIO6': 'pause\t\t\t# music player daemon, toggle pause/play', 'GPIO17': 'toggleplaystop\t\t# music player daemon, toggle stop/start'}`
`connecting to Music Play Daemon (MPD)
host:  127.0.0.1			# host port, can be real IP     port:  6600			# default MPD port number
could not connect to Music Player Daemon, is it running?
`Check: sudo systemctl status mpd`

`pi@moode:/usr/local/maui $ sudo systemctl status mpd`
`mpd.service - Music Player Daemon`
   `Loaded: loaded (/lib/systemd/system/mpd.service; disabled; vendor preset: enabled)`
  ` Active: active (running) since Thu 2021-05-06 11:34:42 EDT; 13min ago`
` Main PID: 1074 (mpd)`
    `Tasks: 3 (limit: 2063)`
  ` CGroup: /system.slice/mpd.service`
          ` └─1074 /usr/local/bin/mpd --no-daemon /etc/mpd.conf`

`May 06 11:34:42 moode systemd[1]: Started Music Player Daemon.`

&nbsp;
**I think there are some missing python-modules?**

**Comment by heddevanderlugt** [comment]
you can test if MDP is listening on this port by using you web browser and
type as address:
172.0.0.1:6600
the response on my computer is:

OK MPD 0.22.0



Op do 6 mei 2021 om 18:17 schreef jimToo ***@***.***>:

**Comment by heddevanderlugt** [comment]
i don't think you are missing python modules, error will be different (at
startup)

please check /etc/mpd.conf for the following lines:

bind_to_address "any"
port "6600"



Op do 6 mei 2021 om 18:17 schreef jimToo ***@***.***>:

**Comment by jimToo** [comment]
/etc/mpd.conf has:
```
bind_to_address "any"
port "6600"
```

Browser is showing:
`OK MPD 0.22.4`



But I can workaround mpd.connect by modifing "mpdi.py":

`Line 40            self.client.connect( str(self.host), str(self.port) )`

change to:
--> `self.client.connect( "127.0.0.1", 6600 )`

then the script can connect to mpd:

- python3 maui.py --verbose --test mpd

- python3 maui.py --verbose --test buttons

both running smooth then.

It seems like the linking in "maui.ini" in the group "Default" is not working:

e.g. _self.musicinfo_ cannot call attributes of group "MPD"
or
e.g. _self.display_ cannot call attributes of group "LCD"

---------------------------------------------------------------

But I have no clue how to solve the last module "LCD":

```
pi@moode:/usr/local/maui $ sudo python3 maui.py --verbose
configuration
<configparser.ConfigParser object at 0x75ce7d90>
{}
{}
mpdata connect
Moode Audio		# welcome text display
Traceback (most recent call last):
  File "maui.py", line 257, in <module>
    maui.task()
  File "maui.py", line 245, in task
    self.info()
  File "maui.py", line 235, in info
    **self.lcd.display( self.infolines[i], i )**
AttributeError: 'NoneType' object has no attribute 'display'
```
I think "self.lcd.display" has some problems calling variables in maui.ini
Can you reproduce these failures with the latest release of moode?

**Comment by heddevanderlugt** [comment]
Hi Jim,
Nice work finding this workaround!

I think the error indicates that the self.lcd object is not declared. It
has no relation to moode i can think of. But i think the problems are all
related with the reading of the ini file.

To test this for the LCD initialisation the fastest test will be to add the
line: print( self.config[self.display]["D4"]  ) after line number 132 in
the original maui.py file (if self.display=="LCD":).
If this is printed with the actual value for D4 as given in the ini-file
the problem must be found somewhere else. Next to check if self.lcd==None
or a actual value (print( self.lcd ) will show.

Regards en keep me informed, nice work, love to see it working.





Op vr 7 mei 2021 om 15:34 schreef jimToo ***@***.***>:

**Comment by jimToo** [comment]
Hi Hedde,
thanks for the hint, I think I got it:

`print( self.config[self.display]["D4"]  )`
is not working:
```
pi@moode:/usr/local/maui $ sudo python3 maui.py --test lcd
Traceback (most recent call last):
  File "maui.py", line 258, in <module>
    maui = MAUI()
  File "maui.py", line 102, in __init__
    self.read_config()
  File "maui.py", line 134, in read_config
    print( self.config["self.display"]["D4"] )
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'self.display'
```

if I change it to:  
`print( self.config["LCD"]["D4"] )`
it's giving out the correct Pin-Number, definied in maui.ini, **BUT also the definition of the pin**:

```
pi@moode:/usr/local/maui $ sudo python3 maui.py --test lcd
GPIO25			# data bit 1 (4 bit mode)
{}
MAUI - MPD Audio User Interface
started in test mode
LCD test is performed, LCD should display testdata
press ctrl-z to end
Traceback (most recent call last):
  File "maui.py", line 275, in <module>
    maui.lcd.display( "performing tests", 0)
AttributeError: 'NoneType' object has no attribute 'display'
```
If I change the maui.ini and remove the comments behind the variable all tests are running smooth!
Thanks! 
My 16x2 OLED is showing weired things for now, but I think that's another topic ; )
Best regards, Jim
